[package]
name = "corsair"
version = "0.0.0-rc1"
authors = ["Brian Mason"]

[dependencies]
clap = "2.33.0"
futures = "0.1.29"
hyper = "0.11.0"
log = "0.3.0"
net2 = "0.2.33"
tokio-core = "0.1.17"

[[bin]]
name = "corsair"
path = "src/main.rs"
