[package]
name = "corsair"
version = "0.0.1"
authors = ["Brian Mason"]

[dependencies]
clap = "2.33.0"
# fastforward = { path = "../fastforward" }
fastforward = "0.5.0"
http = "0.2.9"
term = "0.7.0"

[[bin]]
name = "corsair"
path = "src/main.rs"

